// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "ScreenAgent",
    platforms: [.macOS(.v14)],
    products: [
        .executable(name: "ScreenAgent", targets: ["ScreenAgent"]),
        .library(name: "ScreenAgentCore", targets: ["ScreenAgentCore"]),
    ],
    targets: [
        // All logic lives in the library so it can be unit-tested without launching the app.
        .target(name: "ScreenAgentCore"),
        .executableTarget(name: "ScreenAgent", dependencies: ["ScreenAgentCore"]),
        .testTarget(
            name: "ScreenAgentCoreTests",
            dependencies: ["ScreenAgentCore"],
            // Contract fixtures are generated by backend/tests/test_api_contract.py and read
            // via #filePath, so they don't need to be bundled as resources.
            exclude: ["Fixtures"]
        ),
    ]
)
